apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-svc
  name: nodejs-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30001
  selector:
    app: nodejs-deploy
  type: NodePort