apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-svc
  name: react-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30002
  selector:
    app: react-deploy
  type: NodePort
